### PR TITLE
Support for Symfony 3

### PR DESCRIPTION
**Pull request by Claudiadpn**
Composer.json update in order to be able to use your Bundle in a Symfony 3 application.

### CODE REVIEW

**Comment by shouze** [comment]
@Claudiadpn ci is failing, have you tested it works on a Symfony 3 app?

**Comment by Claudiadpn** [comment]
@shouze Yes we use it in our application (not in prod yet) but API calls are ok.

**Comment by shouze** [comment]
@Claudiadpn ok great, so we have to make the ci green prior to merge anyway, I will probably take some time at the end of the week.

**Comment by shouze** [comment]
Superseded by https://github.com/rezzza/PaymentBe2billBundle/pull/34 that will also fix some edge cases & deprecate some old php versions, so closing this one, thx for your contribution 😉

**Pull request closed without merging**
